### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by NRM129** [NRM129/furima-38877#25]
# 自身のフリマアプリのURL
https://furima-38877.onrender.com/

# Basic認証のIDとパスワード
BASIC_AUTH_USER='tec38877'
BASIC_AUTH_PASSWORD='38877'

# 出品者用のメールアドレスとパスワード
[Mail] hoge@hoge.ne.jp
[PW] a11111

# 購入者用のメールアドレスとパスワード
[Mail] order@order.ne.jp
[PW] b22222

**Comment by snkw-works** [comment]
@NRM129 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **商品出品ページにて、発送までの日数は、「---、1\~2日で発送、2\~3日で発送、4~7日で発送」の4項目が表示されるよう修正しましょう**
「1\~2日で発送」「2\~3日で発送」「4~7日で発送」が正しく表示されていない状態です。
![スクリーンショット_2023-02-09_9_39_16](https://user-images.githubusercontent.com/54050089/217684989-ad2b7027-e43c-4a49-b2b1-c916a769d753.jpg)

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら、以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by NRM129** [comment]
ご確認ありがとうございます。

開発環境、本番環境ともに再度確認しましたが私が見ている画面上では---含む４項目が表示されているのですが、再度ご確認頂けないでしょうか。

開発環境
https://gyazo.com/16f4f23c5cc46033e225dc317fcc0c12
本番環境
https://gyazo.com/054cd9145cd5d1eb147af2245975fa84

**Comment by shodai-ito** [comment]
@NRM129 さん、再度提出ありがとうございます。
伝わりづらい指摘で申し訳ありません。

指摘させていただいた意図としましては、「1~2日」と表示すべき箇所が「1"日"~2日」となっており、余分な"日"が表示されていることかと存じます。
細かい箇所ではございますが、実際の現場でもクライアントから修正を依頼される可能性もございます。
ご理解いただけますと幸いです。

修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by NRM129** [comment]
ご指摘ありがとうございます。
修正いたしました。
宜しくお願い致します。

**Comment by shodai-ito** [comment]
@NRM129 さん、再度ご提出ありがとうございます。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、LGTMとさせていただきます。おめでとうございます！
最終課題「FURIMA」の開発、お疲れ様でした。

`本メッセージ内で、今後の学習についてご案内しています。必ず確認するようにしてください。`

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

------------------------------------------------------------------------------------------
◆ 今後の流れについてのご案内（※詳細は下記リンクのガイダンス資料参照）
------------------------------------------------------------------------------------------
◎この後の期間では、以下のアクションが必要となります。
・最終課題説明文の作成・提出
・FURIMAへの追加機能の実装 または オリジナルアプリ開発
・上記の開発に関する要件定義書の提出
・履歴書と職務経歴書の作成・提出（転職サポートありの方）
・学習成果発表会の準備

◎下記リンク先の「**追加実装・オリジナルアプリ開発 ガイダンス資料**」を必ずご確認ください。
**https://master.tech-camp.in/v2/curriculums/7839**

------------------------------------------------------------------------------------------
◆ さいごに
------------------------------------------------------------------------------------------
◎ガイダンス資料を確認した上で、今後の流れについて不明点がございましたら、担当ライフコーチまでご相談ください。

◎いよいよ卒業までのラストスパートです。これまで頑張ってきたことをフル活用して、最大限の受講成果につなげていきましょう。
![最終課題LGTM](https://user-images.githubusercontent.com/62537107/217705522-4a1f3588-c18d-4935-9a92-05ce45f1465d.png)

**Comment by NRM129** [comment]
ご確認ありがとうございました！
